export type DialCode = {
  key: string;      // ISO 3166-1 alpha-2 country code (NP, IN, ...)
  dial: string;    // E.164 dial prefix (+977)
  label: string;   // Display label (🇳🇵 +977)
  country: string; // Country name
};

export const DIAL_CODES: DialCode[] = [
  { key: "NP", dial: "+977",  label: "🇳🇵 +977",  country: "Nepal" },
  { key: "IN", dial: "+91",   label: "🇮🇳 +91",   country: "India" },
  { key: "US", dial: "+1",    label: "🇺🇸 +1",    country: "United States" },
  { key: "GB", dial: "+44",   label: "🇬🇧 +44",   country: "United Kingdom" },
  { key: "CA", dial: "+1",    label: "🇨🇦 +1",    country: "Canada" },
  { key: "AU", dial: "+61",   label: "🇦🇺 +61",   country: "Australia" },
  { key: "NZ", dial: "+64",   label: "🇳🇿 +64",   country: "New Zealand" },
  { key: "DE", dial: "+49",   label: "🇩🇪 +49",   country: "Germany" },
  { key: "AE", dial: "+971",  label: "🇦🇪 +971",  country: "United Arab Emirates" },
  { key: "BD", dial: "+880",  label: "🇧🇩 +880",  country: "Bangladesh" },
  { key: "AF", dial: "+93",   label: "🇦🇫 +93",   country: "Afghanistan" },
  { key: "AL", dial: "+355",  label: "🇦🇱 +355",  country: "Albania" },
  { key: "DZ", dial: "+213",  label: "🇩🇿 +213",  country: "Algeria" },
  { key: "AD", dial: "+376",  label: "🇦🇩 +376",  country: "Andorra" },
  { key: "AO", dial: "+244",  label: "🇦🇴 +244",  country: "Angola" },
  { key: "AG", dial: "+1268", label: "🇦🇬 +1268", country: "Antigua and Barbuda" },
  { key: "AR", dial: "+54",   label: "🇦🇷 +54",   country: "Argentina" },
  { key: "AM", dial: "+374",  label: "🇦🇲 +374",  country: "Armenia" },
  { key: "AT", dial: "+43",   label: "🇦🇹 +43",   country: "Austria" },
  { key: "AZ", dial: "+994",  label: "🇦🇿 +994",  country: "Azerbaijan" },
  { key: "BS", dial: "+1242", label: "🇧🇸 +1242", country: "Bahamas" },
  { key: "BH", dial: "+973",  label: "🇧🇭 +973",  country: "Bahrain" },
  { key: "BB", dial: "+1246", label: "🇧🇧 +1246", country: "Barbados" },
  { key: "BY", dial: "+375",  label: "🇧🇾 +375",  country: "Belarus" },
  { key: "BE", dial: "+32",   label: "🇧🇪 +32",   country: "Belgium" },
  { key: "BZ", dial: "+501",  label: "🇧🇿 +501",  country: "Belize" },
  { key: "BJ", dial: "+229",  label: "🇧🇯 +229",  country: "Benin" },
  { key: "BT", dial: "+975",  label: "🇧🇹 +975",  country: "Bhutan" },
  { key: "BO", dial: "+591",  label: "🇧🇴 +591",  country: "Bolivia" },
  { key: "BA", dial: "+387",  label: "🇧🇦 +387",  country: "Bosnia and Herzegovina" },
  { key: "BW", dial: "+267",  label: "🇧🇼 +267",  country: "Botswana" },
  { key: "BR", dial: "+55",   label: "🇧🇷 +55",   country: "Brazil" },
  { key: "BN", dial: "+673",  label: "🇧🇳 +673",  country: "Brunei" },
  { key: "BG", dial: "+359",  label: "🇧🇬 +359",  country: "Bulgaria" },
  { key: "BF", dial: "+226",  label: "🇧🇫 +226",  country: "Burkina Faso" },
  { key: "BI", dial: "+257",  label: "🇧🇮 +257",  country: "Burundi" },
  { key: "KH", dial: "+855",  label: "🇰🇭 +855",  country: "Cambodia" },
  { key: "CM", dial: "+237",  label: "🇨🇲 +237",  country: "Cameroon" },
  { key: "CV", dial: "+238",  label: "🇨🇻 +238",  country: "Cape Verde" },
  { key: "CF", dial: "+236",  label: "🇨🇫 +236",  country: "Central African Republic" },
  { key: "TD", dial: "+235",  label: "🇹🇩 +235",  country: "Chad" },
  { key: "CL", dial: "+56",   label: "🇨🇱 +56",   country: "Chile" },
  { key: "CN", dial: "+86",   label: "🇨🇳 +86",   country: "China" },
  { key: "CO", dial: "+57",   label: "🇨🇴 +57",   country: "Colombia" },
  { key: "KM", dial: "+269",  label: "🇰🇲 +269",  country: "Comoros" },
  { key: "CG", dial: "+242",  label: "🇨🇬 +242",  country: "Congo" },
  { key: "CD", dial: "+243",  label: "🇨🇩 +243",  country: "Congo (DRC)" },
  { key: "CR", dial: "+506",  label: "🇨🇷 +506",  country: "Costa Rica" },
  { key: "CI", dial: "+225",  label: "🇨🇮 +225",  country: "Côte d'Ivoire" },
  { key: "HR", dial: "+385",  label: "🇭🇷 +385",  country: "Croatia" },
  { key: "CU", dial: "+53",   label: "🇨🇺 +53",   country: "Cuba" },
  { key: "CY", dial: "+357",  label: "🇨🇾 +357",  country: "Cyprus" },
  { key: "CZ", dial: "+420",  label: "🇨🇿 +420",  country: "Czechia" },
  { key: "DK", dial: "+45",   label: "🇩🇰 +45",   country: "Denmark" },
  { key: "DJ", dial: "+253",  label: "🇩🇯 +253",  country: "Djibouti" },
  { key: "DM", dial: "+1767", label: "🇩🇲 +1767", country: "Dominica" },
  { key: "DO", dial: "+1809", label: "🇩🇴 +1809", country: "Dominican Republic" },
  { key: "EC", dial: "+593",  label: "🇪🇨 +593",  country: "Ecuador" },
  { key: "EG", dial: "+20",   label: "🇪🇬 +20",   country: "Egypt" },
  { key: "SV", dial: "+503",  label: "🇸🇻 +503",  country: "El Salvador" },
  { key: "GQ", dial: "+240",  label: "🇬🇶 +240",  country: "Equatorial Guinea" },
  { key: "ER", dial: "+291",  label: "🇪🇷 +291",  country: "Eritrea" },
  { key: "EE", dial: "+372",  label: "🇪🇪 +372",  country: "Estonia" },
  { key: "SZ", dial: "+268",  label: "🇸🇿 +268",  country: "Eswatini" },
  { key: "ET", dial: "+251",  label: "🇪🇹 +251",  country: "Ethiopia" },
  { key: "FJ", dial: "+679",  label: "🇫🇯 +679",  country: "Fiji" },
  { key: "FI", dial: "+358",  label: "🇫🇮 +358",  country: "Finland" },
  { key: "FR", dial: "+33",   label: "🇫🇷 +33",   country: "France" },
  { key: "GA", dial: "+241",  label: "🇬🇦 +241",  country: "Gabon" },
  { key: "GM", dial: "+220",  label: "🇬🇲 +220",  country: "Gambia" },
  { key: "GE", dial: "+995",  label: "🇬🇪 +995",  country: "Georgia" },
  { key: "GH", dial: "+233",  label: "🇬🇭 +233",  country: "Ghana" },
  { key: "GR", dial: "+30",   label: "🇬🇷 +30",   country: "Greece" },
  { key: "GD", dial: "+1473", label: "🇬🇩 +1473", country: "Grenada" },
  { key: "GT", dial: "+502",  label: "🇬🇹 +502",  country: "Guatemala" },
  { key: "GN", dial: "+224",  label: "🇬🇳 +224",  country: "Guinea" },
  { key: "GW", dial: "+245",  label: "🇬🇼 +245",  country: "Guinea-Bissau" },
  { key: "GY", dial: "+592",  label: "🇬🇾 +592",  country: "Guyana" },
  { key: "HT", dial: "+509",  label: "🇭🇹 +509",  country: "Haiti" },
  { key: "HN", dial: "+504",  label: "🇭🇳 +504",  country: "Honduras" },
  { key: "HK", dial: "+852",  label: "🇭🇰 +852",  country: "Hong Kong" },
  { key: "HU", dial: "+36",   label: "🇭🇺 +36",   country: "Hungary" },
  { key: "IS", dial: "+354",  label: "🇮🇸 +354",  country: "Iceland" },
  { key: "ID", dial: "+62",   label: "🇮🇩 +62",   country: "Indonesia" },
  { key: "IR", dial: "+98",   label: "🇮🇷 +98",   country: "Iran" },
  { key: "IQ", dial: "+964",  label: "🇮🇶 +964",  country: "Iraq" },
  { key: "IE", dial: "+353",  label: "🇮🇪 +353",  country: "Ireland" },
  { key: "IL", dial: "+972",  label: "🇮🇱 +972",  country: "Israel" },
  { key: "IT", dial: "+39",   label: "🇮🇹 +39",   country: "Italy" },
  { key: "JM", dial: "+1876", label: "🇯🇲 +1876", country: "Jamaica" },
  { key: "JP", dial: "+81",   label: "🇯🇵 +81",   country: "Japan" },
  { key: "JO", dial: "+962",  label: "🇯🇴 +962",  country: "Jordan" },
  { key: "KZ", dial: "+7",    label: "🇰🇿 +7",    country: "Kazakhstan" },
  { key: "KE", dial: "+254",  label: "🇰🇪 +254",  country: "Kenya" },
  { key: "KI", dial: "+686",  label: "🇰🇮 +686",  country: "Kiribati" },
  { key: "KW", dial: "+965",  label: "🇰🇼 +965",  country: "Kuwait" },
  { key: "KG", dial: "+996",  label: "🇰🇬 +996",  country: "Kyrgyzstan" },
  { key: "LA", dial: "+856",  label: "🇱🇦 +856",  country: "Laos" },
  { key: "LV", dial: "+371",  label: "🇱🇻 +371",  country: "Latvia" },
  { key: "LB", dial: "+961",  label: "🇱🇧 +961",  country: "Lebanon" },
  { key: "LS", dial: "+266",  label: "🇱🇸 +266",  country: "Lesotho" },
  { key: "LR", dial: "+231",  label: "🇱🇷 +231",  country: "Liberia" },
  { key: "LY", dial: "+218",  label: "🇱🇾 +218",  country: "Libya" },
  { key: "LI", dial: "+423",  label: "🇱🇮 +423",  country: "Liechtenstein" },
  { key: "LT", dial: "+370",  label: "🇱🇹 +370",  country: "Lithuania" },
  { key: "LU", dial: "+352",  label: "🇱🇺 +352",  country: "Luxembourg" },
  { key: "MO", dial: "+853",  label: "🇲🇴 +853",  country: "Macau" },
  { key: "MG", dial: "+261",  label: "🇲🇬 +261",  country: "Madagascar" },
  { key: "MW", dial: "+265",  label: "🇲🇼 +265",  country: "Malawi" },
  { key: "MY", dial: "+60",   label: "🇲🇾 +60",   country: "Malaysia" },
  { key: "MV", dial: "+960",  label: "🇲🇻 +960",  country: "Maldives" },
  { key: "ML", dial: "+223",  label: "🇲🇱 +223",  country: "Mali" },
  { key: "MT", dial: "+356",  label: "🇲🇹 +356",  country: "Malta" },
  { key: "MH", dial: "+692",  label: "🇲🇭 +692",  country: "Marshall Islands" },
  { key: "MR", dial: "+222",  label: "🇲🇷 +222",  country: "Mauritania" },
  { key: "MU", dial: "+230",  label: "🇲🇺 +230",  country: "Mauritius" },
  { key: "MX", dial: "+52",   label: "🇲🇽 +52",   country: "Mexico" },
  { key: "FM", dial: "+691",  label: "🇫🇲 +691",  country: "Micronesia" },
  { key: "MD", dial: "+373",  label: "🇲🇩 +373",  country: "Moldova" },
  { key: "MC", dial: "+377",  label: "🇲🇨 +377",  country: "Monaco" },
  { key: "MN", dial: "+976",  label: "🇲🇳 +976",  country: "Mongolia" },
  { key: "ME", dial: "+382",  label: "🇲🇪 +382",  country: "Montenegro" },
  { key: "MA", dial: "+212",  label: "🇲🇦 +212",  country: "Morocco" },
  { key: "MZ", dial: "+258",  label: "🇲🇿 +258",  country: "Mozambique" },
  { key: "MM", dial: "+95",   label: "🇲🇲 +95",   country: "Myanmar" },
  { key: "NA", dial: "+264",  label: "🇳🇦 +264",  country: "Namibia" },
  { key: "NR", dial: "+674",  label: "🇳🇷 +674",  country: "Nauru" },
  { key: "NL", dial: "+31",   label: "🇳🇱 +31",   country: "Netherlands" },
  { key: "NI", dial: "+505",  label: "🇳🇮 +505",  country: "Nicaragua" },
  { key: "NE", dial: "+227",  label: "🇳🇪 +227",  country: "Niger" },
  { key: "NG", dial: "+234",  label: "🇳🇬 +234",  country: "Nigeria" },
  { key: "KP", dial: "+850",  label: "🇰🇵 +850",  country: "North Korea" },
  { key: "MK", dial: "+389",  label: "🇲🇰 +389",  country: "North Macedonia" },
  { key: "NO", dial: "+47",   label: "🇳🇴 +47",   country: "Norway" },
  { key: "OM", dial: "+968",  label: "🇴🇲 +968",  country: "Oman" },
  { key: "PK", dial: "+92",   label: "🇵🇰 +92",   country: "Pakistan" },
  { key: "PW", dial: "+680",  label: "🇵🇼 +680",  country: "Palau" },
  { key: "PS", dial: "+970",  label: "🇵🇸 +970",  country: "Palestine" },
  { key: "PA", dial: "+507",  label: "🇵🇦 +507",  country: "Panama" },
  { key: "PG", dial: "+675",  label: "🇵🇬 +675",  country: "Papua New Guinea" },
  { key: "PY", dial: "+595",  label: "🇵🇾 +595",  country: "Paraguay" },
  { key: "PE", dial: "+51",   label: "🇵🇪 +51",   country: "Peru" },
  { key: "PH", dial: "+63",   label: "🇵🇭 +63",   country: "Philippines" },
  { key: "PL", dial: "+48",   label: "🇵🇱 +48",   country: "Poland" },
  { key: "PT", dial: "+351",  label: "🇵🇹 +351",  country: "Portugal" },
  { key: "QA", dial: "+974",  label: "🇶🇦 +974",  country: "Qatar" },
  { key: "RO", dial: "+40",   label: "🇷🇴 +40",   country: "Romania" },
  { key: "RU", dial: "+7",    label: "🇷🇺 +7",    country: "Russia" },
  { key: "RW", dial: "+250",  label: "🇷🇼 +250",  country: "Rwanda" },
  { key: "KN", dial: "+1869", label: "🇰🇳 +1869", country: "Saint Kitts and Nevis" },
  { key: "LC", dial: "+1758", label: "🇱🇨 +1758", country: "Saint Lucia" },
  { key: "VC", dial: "+1784", label: "🇻🇨 +1784", country: "Saint Vincent" },
  { key: "WS", dial: "+685",  label: "🇼🇸 +685",  country: "Samoa" },
  { key: "SM", dial: "+378",  label: "🇸🇲 +378",  country: "San Marino" },
  { key: "ST", dial: "+239",  label: "🇸🇹 +239",  country: "São Tomé and Príncipe" },
  { key: "SA", dial: "+966",  label: "🇸🇦 +966",  country: "Saudi Arabia" },
  { key: "SN", dial: "+221",  label: "🇸🇳 +221",  country: "Senegal" },
  { key: "RS", dial: "+381",  label: "🇷🇸 +381",  country: "Serbia" },
  { key: "SC", dial: "+248",  label: "🇸🇨 +248",  country: "Seychelles" },
  { key: "SL", dial: "+232",  label: "🇸🇱 +232",  country: "Sierra Leone" },
  { key: "SG", dial: "+65",   label: "🇸🇬 +65",   country: "Singapore" },
  { key: "SK", dial: "+421",  label: "🇸🇰 +421",  country: "Slovakia" },
  { key: "SI", dial: "+386",  label: "🇸🇮 +386",  country: "Slovenia" },
  { key: "SB", dial: "+677",  label: "🇸🇧 +677",  country: "Solomon Islands" },
  { key: "SO", dial: "+252",  label: "🇸🇴 +252",  country: "Somalia" },
  { key: "ZA", dial: "+27",   label: "🇿🇦 +27",   country: "South Africa" },
  { key: "KR", dial: "+82",   label: "🇰🇷 +82",   country: "South Korea" },
  { key: "SS", dial: "+211",  label: "🇸🇸 +211",  country: "South Sudan" },
  { key: "ES", dial: "+34",   label: "🇪🇸 +34",   country: "Spain" },
  { key: "LK", dial: "+94",   label: "🇱🇰 +94",   country: "Sri Lanka" },
  { key: "SD", dial: "+249",  label: "🇸🇩 +249",  country: "Sudan" },
  { key: "SR", dial: "+597",  label: "🇸🇷 +597",  country: "Suriname" },
  { key: "SE", dial: "+46",   label: "🇸🇪 +46",   country: "Sweden" },
  { key: "CH", dial: "+41",   label: "🇨🇭 +41",   country: "Switzerland" },
  { key: "SY", dial: "+963",  label: "🇸🇾 +963",  country: "Syria" },
  { key: "TW", dial: "+886",  label: "🇹🇼 +886",  country: "Taiwan" },
  { key: "TJ", dial: "+992",  label: "🇹🇯 +992",  country: "Tajikistan" },
  { key: "TZ", dial: "+255",  label: "🇹🇿 +255",  country: "Tanzania" },
  { key: "TH", dial: "+66",   label: "🇹🇭 +66",   country: "Thailand" },
  { key: "TL", dial: "+670",  label: "🇹🇱 +670",  country: "Timor-Leste" },
  { key: "TG", dial: "+228",  label: "🇹🇬 +228",  country: "Togo" },
  { key: "TO", dial: "+676",  label: "🇹🇴 +676",  country: "Tonga" },
  { key: "TT", dial: "+1868", label: "🇹🇹 +1868", country: "Trinidad and Tobago" },
  { key: "TN", dial: "+216",  label: "🇹🇳 +216",  country: "Tunisia" },
  { key: "TR", dial: "+90",   label: "🇹🇷 +90",   country: "Turkey" },
  { key: "TM", dial: "+993",  label: "🇹🇲 +993",  country: "Turkmenistan" },
  { key: "TV", dial: "+688",  label: "🇹🇻 +688",  country: "Tuvalu" },
  { key: "UG", dial: "+256",  label: "🇺🇬 +256",  country: "Uganda" },
  { key: "UA", dial: "+380",  label: "🇺🇦 +380",  country: "Ukraine" },
  { key: "UY", dial: "+598",  label: "🇺🇾 +598",  country: "Uruguay" },
  { key: "UZ", dial: "+998",  label: "🇺🇿 +998",  country: "Uzbekistan" },
  { key: "VU", dial: "+678",  label: "🇻🇺 +678",  country: "Vanuatu" },
  { key: "VA", dial: "+379",  label: "🇻🇦 +379",  country: "Vatican City" },
  { key: "VE", dial: "+58",   label: "🇻🇪 +58",   country: "Venezuela" },
  { key: "VN", dial: "+84",   label: "🇻🇳 +84",   country: "Vietnam" },
  { key: "YE", dial: "+967",  label: "🇾🇪 +967",  country: "Yemen" },
  { key: "ZM", dial: "+260",  label: "🇿🇲 +260",  country: "Zambia" },
  { key: "ZW", dial: "+263",  label: "🇿🇼 +263",  country: "Zimbabwe" },
];

export const dialSpec = (key: string): DialCode =>
  DIAL_CODES.find((d) => d.key === key) ?? DIAL_CODES[0];

export const phoneDigits = (s: string): string => s.replace(/\D/g, "");

/** E.164 spec: 7–15 digits (excluding the dial prefix) */
export const isValidPhoneLength = (s: string): boolean => {
  const n = phoneDigits(s).length;
  return n >= 7 && n <= 15;
};
