export interface University {
  name: string;
  logo: string;
  country: string;
}

export const allUniversities: University[] = [
  // UK
  { name: "Buckinghamshire New University", logo: "/images/universities/uk/Buckinghamshire-New-University.webp", country: "UK" },
  { name: "BPP University", logo: "/images/universities/uk/BPP-University.webp", country: "UK" },
  { name: "Coventry University", logo: "/images/universities/uk/Coventry-University.webp", country: "UK" },
  { name: "Health Sciences University", logo: "/images/universities/uk/Health-Sciences-University.webp", country: "UK" },
  { name: "Ravensbourne University London", logo: "/images/universities/uk/Ravensbourne-University-London.webp", country: "UK" },
  { name: "University of Sunderland", logo: "/images/universities/uk/University-of-Sunderland.webp", country: "UK" },
  { name: "University of East London", logo: "/images/universities/uk/University-of-East-London.webp", country: "UK" },
  { name: "Ulster University", logo: "/images/universities/uk/Ulster-University.webp", country: "UK" },
  { name: "University of Greenwich", logo: "/images/universities/uk/University-of-Greenwich.webp", country: "UK" },
  { name: "The University of Law", logo: "/images/universities/uk/The-University-of-Law.webp", country: "UK" },
  { name: "University of Roehampton", logo: "/images/universities/uk/University-of-Roehampton.webp", country: "UK" },
  { name: "University of Worcester", logo: "/images/universities/uk/University-of-Worcester.webp", country: "UK" },
  { name: "University of West London", logo: "/images/universities/uk/University-of-West-London.webp", country: "UK" },
  { name: "University of the West of Scotland", logo: "/images/universities/uk/University-of-the-West-of-Scotland.webp", country: "UK" },
  { name: "York St John University", logo: "/images/universities/uk/York-St-John-University.webp", country: "UK" },
  // USA
  { name: "Colorado State University", logo: "/images/universities/usa/COLORADO.webp", country: "USA" },
  { name: "Webster University", logo: "/images/universities/usa/webster-1.webp", country: "USA" },
  { name: "Avila University", logo: "/images/universities/usa/AVILA.webp", country: "USA" },
  { name: "Concordia University", logo: "/images/universities/usa/CONCORDIA.webp", country: "USA" },
  { name: "Southeast Missouri State", logo: "/images/universities/usa/SOUTHEAST-MISSOURI.webp", country: "USA" },
  { name: "Herzing University", logo: "/images/universities/usa/HERZING.webp", country: "USA" },
  { name: "Wright State University", logo: "/images/universities/usa/WRIGHT-STATE.webp", country: "USA" },
  { name: "Washington University", logo: "/images/universities/usa/WASHINGTON.webp", country: "USA" },
  { name: "Texas State University", logo: "/images/universities/usa/TEXAS.webp", country: "USA" },
  { name: "Murray State University", logo: "/images/universities/usa/MURRAY.webp", country: "USA" },
  { name: "Youngstown State University", logo: "/images/universities/usa/YOUNGSTOWN.webp", country: "USA" },
  { name: "University of Central Arkansas", logo: "/images/universities/usa/CENTRAL-ARKANSAS.webp", country: "USA" },
  { name: "Dakota State University", logo: "/images/universities/usa/DAKOTA-STATE.webp", country: "USA" },
  { name: "University of South Dakota", logo: "/images/universities/usa/UNIVERSITY-F-SOUTH-DAKOTA.webp", country: "USA" },
  { name: "Pacific Oaks College", logo: "/images/universities/usa/PACIFIC.webp", country: "USA" },
  { name: "Bethesda University", logo: "/images/universities/usa/BETHESDA.webp", country: "USA" },
  { name: "St. Cloud State University", logo: "/images/universities/usa/ST-CLOUD.webp", country: "USA" },
  { name: "South Dakota State University", logo: "/images/universities/usa/South.webp", country: "USA" },
  { name: "Post University", logo: "/images/universities/usa/POST.webp", country: "USA" },
  { name: "Northwest Missouri State", logo: "/images/universities/usa/NORTHWEST.webp", country: "USA" },
  { name: "University of Central Missouri", logo: "/images/universities/usa/university-f.webp", country: "USA" },
  { name: "Minnesota State University", logo: "/images/universities/usa/MINNESOTA-STATE.webp", country: "USA" },
  // Australia
  { name: "Western Sydney University", logo: "/images/universities/australia/western-sydney-university.webp", country: "Australia" },
  { name: "La Trobe University", logo: "/images/universities/australia/la-trobe-university.webp", country: "Australia" },
  { name: "Victoria University", logo: "/images/universities/australia/victoria-university.webp", country: "Australia" },
  { name: "University of Queensland", logo: "/images/universities/australia/university-of-queensland.webp", country: "Australia" },
  { name: "Monash University", logo: "/images/universities/australia/monash-university.webp", country: "Australia" },
  { name: "Kaplan Business School", logo: "/images/universities/australia/kaplan-business-school.webp", country: "Australia" },
  { name: "Southern Cross University", logo: "/images/universities/australia/southern-cross-university.webp", country: "Australia" },
  { name: "RMIT University", logo: "/images/universities/australia/rmit-university.webp", country: "Australia" },
  { name: "Macquarie University", logo: "/images/universities/australia/macquarie-university.webp", country: "Australia" },
  { name: "University of Tasmania", logo: "/images/universities/australia/university-of-tasmania.webp", country: "Australia" },
  // Canada
  { name: "University of Toronto", logo: "/images/universities/canada/university-of-toronto.webp", country: "Canada" },
  { name: "University of British Columbia", logo: "/images/universities/canada/university-of-british-columbia.webp", country: "Canada" },
  { name: "McGill University", logo: "/images/universities/canada/mcgill-university.webp", country: "Canada" },
  { name: "University of Alberta", logo: "/images/universities/canada/university-of-alberta.webp", country: "Canada" },
  { name: "McMaster University", logo: "/images/universities/canada/mcmaster-university.webp", country: "Canada" },
  { name: "University of Waterloo", logo: "/images/universities/canada/university-of-waterloo.webp", country: "Canada" },
  { name: "Western University", logo: "/images/universities/canada/western-university.webp", country: "Canada" },
  { name: "Queen's University", logo: "/images/universities/canada/queens-university.webp", country: "Canada" },
  { name: "Simon Fraser University", logo: "/images/universities/canada/simon-fraser-university.webp", country: "Canada" },
  { name: "Dalhousie University", logo: "/images/universities/canada/dalhousie-university.webp", country: "Canada" },
  // France
  { name: "Sorbonne University", logo: "/images/universities/france/sorbonne-university.webp", country: "France" },
  { name: "Universite PSL", logo: "/images/universities/france/universite-psl.svg", country: "France" },
  { name: "Universite Grenoble Alpes", logo: "/images/universities/france/universite-grenoble-alpes.webp", country: "France" },
  { name: "Aix-Marseille University", logo: "/images/universities/france/aix-marseille-university.webp", country: "France" },
  { name: "Universite de Strasbourg", logo: "/images/universities/france/universite-de-strasbourg.webp", country: "France" },
  { name: "Universite de Bordeaux", logo: "/images/universities/france/universite-de-bordeaux.webp", country: "France" },
  { name: "Sciences Po", logo: "/images/universities/france/sciences-po.webp", country: "France" },
  { name: "Ecole Polytechnique", logo: "/images/universities/france/ecole-polytechnique.webp", country: "France" },
  { name: "Universite de Lille", logo: "/images/universities/france/universite-de-lille.webp", country: "France" },
  { name: "University of Paris-Saclay", logo: "/images/universities/france/university-of-paris-saclay.webp", country: "France" },
  // Finland
  { name: "Haaga-Helia University of Applied Science", logo: "/images/universities/finland/haaga-helia.webp", country: "Finland" },
  { name: "South-Eastern Finland University of Applied Science", logo: "/images/universities/finland/south-eastern-finland.webp", country: "Finland" },
  { name: "Lab University of Applied Science", logo: "/images/universities/finland/lab-university.webp", country: "Finland" },
  { name: "Satakunta University of Applied Science", logo: "/images/universities/finland/satakunta-university.webp", country: "Finland" },
  { name: "Vaasa University of Applied Science", logo: "/images/universities/finland/vaasa-university.webp", country: "Finland" },
  { name: "Karelia University of Applied Science", logo: "/images/universities/finland/karelia-university.webp", country: "Finland" },
  // New Zealand
  { name: "University of Auckland", logo: "/images/universities/newzealand/university-of-auckland.webp", country: "New Zealand" },
  { name: "University of Otago", logo: "/images/universities/newzealand/university-of-otago.webp", country: "New Zealand" },
  { name: "Victoria University of Wellington", logo: "/images/universities/newzealand/victoria-university-of-wellington.webp", country: "New Zealand" },
  { name: "University of Canterbury", logo: "/images/universities/newzealand/university-of-canterbury.webp", country: "New Zealand" },
  { name: "Massey University", logo: "/images/universities/newzealand/massey-university.webp", country: "New Zealand" },
  { name: "Auckland University of Technology", logo: "/images/universities/newzealand/auckland-university-of-technology.webp", country: "New Zealand" },
  { name: "Lincoln University", logo: "/images/universities/newzealand/lincoln-university.webp", country: "New Zealand" },
  { name: "Unitec Institute of Technology", logo: "/images/universities/newzealand/unitec-institute-of-technology.webp", country: "New Zealand" },
  { name: "Eastern Institute of Technology", logo: "/images/universities/newzealand/eastern-institute-of-technology.webp", country: "New Zealand" },
  { name: "Southern Institute of Technology", logo: "/images/universities/newzealand/southern-institute-of-technology.webp", country: "New Zealand" },
  // India
  { name: "Vellore Institute of Technology (VIT)", logo: "/images/universities/india/vit.webp", country: "India" },
  { name: "University of Delhi", logo: "/images/universities/india/university-of-delhi.webp", country: "India" },
  { name: "Jawaharlal Nehru University", logo: "/images/universities/india/jawaharlal-nehru-university.webp", country: "India" },
  { name: "Banaras Hindu University", logo: "/images/universities/india/banaras-hindu-university.webp", country: "India" },
  { name: "Anna University", logo: "/images/universities/india/anna-university.webp", country: "India" },
  { name: "Manipal Academy of Higher Education", logo: "/images/universities/india/manipal-academy.webp", country: "India" },
  { name: "Kalinga Institute of Technology", logo: "/images/universities/india/kalinga-institute.webp", country: "India" },
  { name: "RK University", logo: "/images/universities/india/rk-university.webp", country: "India" },
  { name: "IISc Bangalore", logo: "/images/universities/india/iisc-bangalore.webp", country: "India" },
  { name: "Delhi Technological University (DTU)", logo: "/images/universities/india/delhi-technological-university.webp", country: "India" },
  { name: "Symbiosis International University", logo: "/images/universities/india/symbiosis-international-university.webp", country: "India" },
  // Germany
  { name: "Technical University of Munich", logo: "/images/universities/germany/technical-university-of-munich.webp", country: "Germany" },
  { name: "Ludwig-Maximilians-Universität München", logo: "/images/universities/germany/ludwig-maximilians-universitat.webp", country: "Germany" },
  { name: "Heidelberg University", logo: "/images/universities/germany/heidelberg-university.webp", country: "Germany" },
  { name: "Freie Universität Berlin", logo: "/images/universities/germany/freie-universitat-berlin.webp", country: "Germany" },
  { name: "Karlsruhe Institute of Technology", logo: "/images/universities/germany/karlsruhe-institute-of-technology.webp", country: "Germany" },
  { name: "RWTH Aachen University", logo: "/images/universities/germany/rwth-aachen-university.webp", country: "Germany" },
  { name: "Technische Universität Berlin", logo: "/images/universities/germany/technische-universitat-berlin.webp", country: "Germany" },
  { name: "University of Hamburg", logo: "/images/universities/germany/university-of-hamburg.webp", country: "Germany" },
  { name: "University of Freiburg", logo: "/images/universities/germany/university-of-freiburg.webp", country: "Germany" },
  { name: "Humboldt-Universität zu Berlin", logo: "/images/universities/germany/humboldt-universitat-berlin.webp", country: "Germany" },
];
