// Mock match-winners data for the Predictors' Circle section.
// Real CRM endpoint not yet built — when it ships, swap this module
// for a fetcher returning the same MatchWinner[] shape.
//
// Future endpoint contract:
//   GET https://edgex.zunkireelabs.com/api/public/campaigns/{id}/match-winners
//   Response: { data: { campaign: {...}, winners: MatchWinner[] } }

export type MatchStage = "group" | "r32" | "r16" | "qf" | "sf" | "final";
export type MatchOutcome = "team_a" | "team_b" | "draw";
export type MatchStatus = "scheduled" | "live" | "final";

export interface MatchWinner {
  match_id: string;
  match_label: string;
  team_a: { code: string; name: string; flag: string };
  team_b: { code: string; name: string; flag: string };
  score: string | null;
  outcome: MatchOutcome | null;
  status: MatchStatus;
  kickoff: string;
  stage: MatchStage;
  winner: {
    name: string;
    picked: MatchOutcome;
  } | null;
}

const flag = (code: string) => `https://a.espncdn.com/i/teamlogos/countries/500/${code.toLowerCase()}.png`;

export const MOCK_MATCH_WINNERS: MatchWinner[] = [
  {
    match_id: "espn-760301",
    match_label: "Saudi Arabia vs Uruguay",
    team_a: { code: "KSA", name: "Saudi Arabia", flag: flag("ksa") },
    team_b: { code: "URU", name: "Uruguay", flag: flag("uru") },
    score: "1–1",
    outcome: "draw",
    status: "final",
    kickoff: "2026-06-11T17:00:00Z",
    stage: "group",
    winner: { name: "Bishwo P.", picked: "draw" },
  },
  {
    match_id: "espn-760302",
    match_label: "United States vs Paraguay",
    team_a: { code: "USA", name: "United States", flag: flag("usa") },
    team_b: { code: "PAR", name: "Paraguay", flag: flag("par") },
    score: "4–1",
    outcome: "team_a",
    status: "final",
    kickoff: "2026-06-11T20:00:00Z",
    stage: "group",
    winner: { name: "Milan K.", picked: "team_a" },
  },
  {
    match_id: "espn-760303",
    match_label: "France vs Senegal",
    team_a: { code: "FRA", name: "France", flag: flag("fra") },
    team_b: { code: "SEN", name: "Senegal", flag: flag("sen") },
    score: "3–1",
    outcome: "team_a",
    status: "final",
    kickoff: "2026-06-12T15:00:00Z",
    stage: "group",
    winner: { name: "Ebish P.", picked: "team_a" },
  },
  {
    match_id: "espn-760304",
    match_label: "Austria vs Jordan",
    team_a: { code: "AUT", name: "Austria", flag: flag("aut") },
    team_b: { code: "JOR", name: "Jordan", flag: flag("jor") },
    score: "3–1",
    outcome: "team_a",
    status: "final",
    kickoff: "2026-06-12T18:00:00Z",
    stage: "group",
    winner: { name: "Eshori P.", picked: "team_a" },
  },
  {
    match_id: "espn-760305",
    match_label: "Iran vs New Zealand",
    team_a: { code: "IRN", name: "Iran", flag: flag("irn") },
    team_b: { code: "NZL", name: "New Zealand", flag: flag("nzl") },
    score: "2–2",
    outcome: "draw",
    status: "final",
    kickoff: "2026-06-12T21:00:00Z",
    stage: "group",
    winner: { name: "Gautam S.", picked: "draw" },
  },
  {
    match_id: "espn-760306",
    match_label: "Germany vs Curaçao",
    team_a: { code: "GER", name: "Germany", flag: flag("ger") },
    team_b: { code: "CUW", name: "Curaçao", flag: flag("cuw") },
    score: "7–1",
    outcome: "team_a",
    status: "final",
    kickoff: "2026-06-13T15:00:00Z",
    stage: "group",
    winner: { name: "Jebish P.", picked: "team_a" },
  },
  {
    match_id: "espn-760307",
    match_label: "South Korea vs Czechia",
    team_a: { code: "KOR", name: "South Korea", flag: flag("kor") },
    team_b: { code: "CZE", name: "Czechia", flag: flag("cze") },
    score: "2–1",
    outcome: "team_a",
    status: "final",
    kickoff: "2026-06-13T18:00:00Z",
    stage: "group",
    winner: { name: "Bishwo P.", picked: "team_a" },
  },
  {
    match_id: "espn-760308",
    match_label: "Canada vs Bosnia-Herzegovina",
    team_a: { code: "CAN", name: "Canada", flag: flag("can") },
    team_b: { code: "BIH", name: "Bosnia-Herzegovina", flag: flag("bih") },
    score: "1–1",
    outcome: "draw",
    status: "final",
    kickoff: "2026-06-13T21:00:00Z",
    stage: "group",
    winner: { name: "Shivam R.", picked: "draw" },
  },
  {
    match_id: "espn-760309",
    match_label: "Netherlands vs Japan",
    team_a: { code: "NED", name: "Netherlands", flag: flag("ned") },
    team_b: { code: "JPN", name: "Japan", flag: flag("jpn") },
    score: "2–2",
    outcome: "draw",
    status: "final",
    kickoff: "2026-06-14T13:00:00Z",
    stage: "group",
    winner: { name: "Arjab K.", picked: "draw" },
  },
  {
    match_id: "espn-760310",
    match_label: "Ivory Coast vs Ecuador",
    team_a: { code: "CIV", name: "Ivory Coast", flag: flag("civ") },
    team_b: { code: "ECU", name: "Ecuador", flag: flag("ecu") },
    score: "1–0",
    outcome: "team_a",
    status: "final",
    kickoff: "2026-06-14T16:00:00Z",
    stage: "group",
    winner: { name: "Ujjwol H.", picked: "team_a" },
  },
  {
    match_id: "espn-760311",
    match_label: "Belgium vs Egypt",
    team_a: { code: "BEL", name: "Belgium", flag: flag("bel") },
    team_b: { code: "EGY", name: "Egypt", flag: flag("egy") },
    score: "1–1",
    outcome: "draw",
    status: "final",
    kickoff: "2026-06-14T19:00:00Z",
    stage: "group",
    winner: { name: "Milan K.", picked: "draw" },
  },
  {
    match_id: "espn-760312",
    match_label: "Mexico vs South Africa",
    team_a: { code: "MEX", name: "Mexico", flag: flag("mex") },
    team_b: { code: "RSA", name: "South Africa", flag: flag("rsa") },
    score: "2–0",
    outcome: "team_a",
    status: "final",
    kickoff: "2026-06-14T22:00:00Z",
    stage: "group",
    winner: { name: "Pitamber B.", picked: "team_a" },
  },
  {
    match_id: "espn-760313",
    match_label: "Iraq vs Norway",
    team_a: { code: "IRQ", name: "Iraq", flag: flag("irq") },
    team_b: { code: "NOR", name: "Norway", flag: flag("nor") },
    score: "1–4",
    outcome: "team_b",
    status: "final",
    kickoff: "2026-06-15T14:00:00Z",
    stage: "group",
    winner: { name: "Prashant T.", picked: "team_b" },
  },
  {
    match_id: "espn-760314",
    match_label: "Spain vs Cape Verde",
    team_a: { code: "ESP", name: "Spain", flag: flag("esp") },
    team_b: { code: "CPV", name: "Cape Verde", flag: flag("cpv") },
    score: "0–0",
    outcome: "draw",
    status: "final",
    kickoff: "2026-06-15T17:00:00Z",
    stage: "group",
    winner: { name: "Rajan S.", picked: "draw" },
  },
  {
    match_id: "espn-760315",
    match_label: "Australia vs Türkiye",
    team_a: { code: "AUS", name: "Australia", flag: flag("aus") },
    team_b: { code: "TUR", name: "Türkiye", flag: flag("tur") },
    score: "2–0",
    outcome: "team_a",
    status: "final",
    kickoff: "2026-06-15T20:00:00Z",
    stage: "group",
    winner: { name: "Kishor J.", picked: "team_a" },
  },
  {
    match_id: "espn-760316",
    match_label: "Brazil vs Morocco",
    team_a: { code: "BRA", name: "Brazil", flag: flag("bra") },
    team_b: { code: "MAR", name: "Morocco", flag: flag("mar") },
    score: "1–1",
    outcome: "draw",
    status: "final",
    kickoff: "2026-06-16T14:00:00Z",
    stage: "group",
    winner: { name: "Ebish P.", picked: "draw" },
  },
  {
    match_id: "espn-760317",
    match_label: "Sweden vs Tunisia",
    team_a: { code: "SWE", name: "Sweden", flag: flag("swe") },
    team_b: { code: "TUN", name: "Tunisia", flag: flag("tun") },
    score: "5–1",
    outcome: "team_a",
    status: "final",
    kickoff: "2026-06-16T17:00:00Z",
    stage: "group",
    winner: { name: "Rohit A.", picked: "team_a" },
  },
  {
    match_id: "espn-760318",
    match_label: "Uzbekistan vs Colombia",
    team_a: { code: "UZB", name: "Uzbekistan", flag: flag("uzb") },
    team_b: { code: "COL", name: "Colombia", flag: flag("col") },
    score: "1–3",
    outcome: "team_b",
    status: "final",
    kickoff: "2026-06-16T20:00:00Z",
    stage: "group",
    winner: { name: "Prince T.", picked: "team_b" },
  },
  {
    match_id: "espn-760319",
    match_label: "Argentina vs Algeria",
    team_a: { code: "ARG", name: "Argentina", flag: flag("arg") },
    team_b: { code: "ALG", name: "Algeria", flag: flag("alg") },
    score: "3–0",
    outcome: "team_a",
    status: "final",
    kickoff: "2026-06-17T14:00:00Z",
    stage: "group",
    winner: { name: "Binay D.", picked: "team_a" },
  },
  {
    match_id: "espn-760320",
    match_label: "Haiti vs Scotland",
    team_a: { code: "HAI", name: "Haiti", flag: flag("hai") },
    team_b: { code: "SCO", name: "Scotland", flag: flag("sco") },
    score: "0–1",
    outcome: "team_b",
    status: "final",
    kickoff: "2026-06-17T17:00:00Z",
    stage: "group",
    winner: { name: "Prajwol H.", picked: "team_b" },
  },
  {
    match_id: "espn-760321",
    match_label: "England vs Croatia",
    team_a: { code: "ENG", name: "England", flag: flag("eng") },
    team_b: { code: "CRO", name: "Croatia", flag: flag("cro") },
    score: "4–2",
    outcome: "team_a",
    status: "final",
    kickoff: "2026-06-17T20:00:00Z",
    stage: "group",
    winner: { name: "Raviranjan T.", picked: "team_a" },
  },
  {
    match_id: "espn-760322",
    match_label: "Ghana vs Panama",
    team_a: { code: "GHA", name: "Ghana", flag: flag("gha") },
    team_b: { code: "PAN", name: "Panama", flag: flag("pan") },
    score: "1–0",
    outcome: "team_a",
    status: "final",
    kickoff: "2026-06-18T14:00:00Z",
    stage: "group",
    winner: { name: "Sahil A.", picked: "team_a" },
  },
  {
    match_id: "espn-760323",
    match_label: "Qatar vs Switzerland",
    team_a: { code: "QAT", name: "Qatar", flag: flag("qat") },
    team_b: { code: "SUI", name: "Switzerland", flag: flag("sui") },
    score: "1–1",
    outcome: "draw",
    status: "final",
    kickoff: "2026-06-18T17:00:00Z",
    stage: "group",
    winner: null, // CRM hasn't picked a winner yet
  },
  {
    match_id: "espn-760324",
    match_label: "Portugal vs Congo DR",
    team_a: { code: "POR", name: "Portugal", flag: flag("por") },
    team_b: { code: "COD", name: "Congo DR", flag: flag("cod") },
    score: "1–1",
    outcome: "draw",
    status: "final",
    kickoff: "2026-06-18T20:00:00Z",
    stage: "group",
    winner: { name: "Bishwo P.", picked: "draw" },
  },
];

export function getMockMatchWinners(): MatchWinner[] {
  return MOCK_MATCH_WINNERS;
}
